apiVersion: v2
appVersion: v4.72.0
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 14.0.3
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.1.6
description: A Helm chart for Fleet
home: https://github.com/fleetdm/fleet
keywords:
- fleet
- osquery
name: fleet
sources:
- https://github.com/fleetdm/fleet.git
version: v6.6.12
